// @flow
import type { DefaultYoungTravelerParentConsentType } from 'src/wcm/flow-typed/wcm.types';

export const defaultYoungTravelerParentConsent: DefaultYoungTravelerParentConsentType = {
  body: [
    {
      type: 'text',
      value:
        '<p class="p3"><strong>&bull; </strong>Southwest&reg; considers children ages 12 through 17 traveling alone to be Young Travelers, not Unaccompanied Minors. Accordingly, Southwest&reg; Unaccompanied Minor procedures do not apply to ages 12 through 17.</p>\n<p class="p3"><strong>&bull; </strong>Parents/Guardians are responsible for ensuring a Young Traveler arrives for check-in and boarding in accordance with each airport\'s suggested arrival time. The amount of time to park, check luggage, pass through the security checkpoint, and board the flight varies based on each airport\'s size, configuration, and travel season.</p>\n<p class="p3"><strong>&bull; </strong>Your child has sufficient maturity and capability to travel alone (this includes, but is not limited to, checking in, passing through the security checkpoint, boarding, deplaning, and claiming luggage), without adult supervision or assistance from Southwest&reg; Employees, on all scheduled service: nonstop, same-plane service with intermediate stops, and connecting service that requires your child to change planes.</p>\n<p class="p3"><strong>&bull; </strong>Parents/Guardians wishing to escort a Young Traveler to/from the gate must obtain a Non-Passenger Escort (NPE) from the ticket counter in order to pass through the security checkpoint. Each airport may impose restrictions on NPEs being issued based on guidance from the local Transportation Security Administration directives.</p>\n<p class="p3"><strong>&bull; </strong>Southwest&reg; does not monitor Young Travelers during travel. Accordingly, each Young Traveler must have sufficient maturity and capability to request assistance from a Southwest&reg; Employee if needed and the means to contact a parent/guardian if there is a travel disruption.</p>\n<p class="p3"><strong>&bull; </strong>Southwest Airlines&reg; reserves the right not to allow travel on flights that may be delayed, diverted, or cancelled due to weather or other operational disruptions.</p>\n<p class="p3"><strong>&bull; </strong>Southwest Airlines&reg; does not provide Young Traveler service to/from international destinations.</p>\n<p class="p3"><strong>&bull; </strong>Southwest Airlines&reg; does not assume responsibility for any Young Traveler\'s actions. THE PURCHASER AGREES TO INDEMNIFY, HOLD HARMLESS, AND FULLY RELEASE SOUTHWEST AIRLINES&reg; FOR ANY AND ALL INJURY OR DAMAGES TO PROPERTY OR PERSONS CAUSED BY OR INCURRED AS A RESULT OF A YOUNG TRAVELER\'S ACTIONS, INCLUDING INJURIES TO THE YOUNG TRAVELER CAUSED BY HIS OR HER OWN NEGLIGENCE.</p>'
    }
  ],
  title: 'Young Traveler parent consent'
};
