import i18n from '@swa-ui/locale';

export const CONFIRMATION_NUMBER_SUBTITLE = {
  CONFIRMATION_NUMBER: 'Confirmation # %s'
};
export const MY_ACCOUNT_FLIGHT_CARD = {
  CHECK_PRICE: 'Check price',
  REBOOK_IT: 'Rebook it'
};
export const TIER_BENEFITS = {
  DEFAULT_BENEFIT_FLY_BY: 'Fly By',
  DEFAULT_BENEFIT_PRIORITY_BOARDING: 'Priority Boarding',
  DEFAULT_BENEFIT_PRIORITY_SECURITY_LINE: '(Priority Security Line)',
  DEFAULT_BENEFIT_STANDBY_PRIORITY: 'Standby Priority',
  DEFAULT_BENEFIT_WIFI: 'Free Inflight WiFi'
};
export const RAPID_REWARDS_PAGE = {
  TIER_PRESTRING_MAP: {
    CLIMBING: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__TIER_PRESTRING_MAP__CLIMBING'),
    MAINTAIN: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__TIER_PRESTRING_MAP__MAINTAIN'),
    CONGRATULATIONS: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__TIER_PRESTRING_MAP__CONGRATULATIONS')
  },
  COMPANIONPASS_PRESTRING_MAP: {
    CLIMBING: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__COMPANIONPASS_PRESTRING_MAP__CLIMBING'),
    MAINTAIN: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__COMPANIONPASS_PRESTRING_MAP__MAINTAIN'),
    CONGRATULATIONS: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__COMPANIONPASS_PRESTRING_MAP__CONGRATULATIONS')
  },
  LABEL_MAP: {
    NON_ELITE: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__LABEL_MAP__NON_ELITE'),
    A_LIST: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__LABEL_MAP__A_LIST'),
    A_LIST_PREFERRED: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__LABEL_MAP__A_LIST_PREFERRED')
  },
  STATUS_MAP: {
    A_LIST: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__STATUS_MAP__A_LIST'),
    A_LIST_PREFERRED: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__STATUS_MAP__A_LIST_PREFERRED')
  },
  NON_ELITE: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__NON_ELITE'),
  CLIMBING: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__CLIMBING'),
  MAINTAIN: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__MAINTAIN'),
  CONGRATULATIONS: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__CONGRATULATIONS'),
  COMPANIONPASS: i18n('MY_ACCOUNT__RAPID_REWARDS_PAGE__COMPANIONPASS'),
  STATUS_WITH_DOT: ' status.',
  DOT: '.'
};
export const UNUSED_FUNDS_CONSTANT = {
  VIEW_FUNDS_TARGET: 'https://southwest.com/flight/login?returnUrl=%2Fmyaccount%3Fclk%3DGSUBNAV-RR-ACCOUNT',
  LEARN_MORE_TARGET: 'https://southwest.com/html/customer-service/faqs.html?clk=GFOOTER-CUSTOMER-FAQ'
};
