export default {
  NATIONALITY: 'NATIONALITY',
  EMERGENCY_CONTACT: 'EMERGENCY_CONTACT',
  PASSPORT: 'PASSPORT',
  VISA: 'VISA',
  PERMANENT_RESIDENT_CARD: 'PERMANENT_RESIDENT_CARD',
  DESTINATION: 'DESTINATION'
};
