export default {
  HOME_PAGE_MBOX1_ID: 'swa_mweb_homeHero01',
  HOME_PAGE_MBOX2_ID: 'swa_mweb_homeHero02',
  RAPID_REWARDS_MBOX_ID: 'swa_mweb_rapidRewardsIndexpromoBanner03',
  PRICING_CHASE_MBOX_ID: 'swa_mweb_airBookingPriceFullChaseAd',
  PRICE_PROMO_MIDDLE1_MBOX_ID: 'mWebAirPricePromoMiddle01',
  PURCHASE_PAGE_MBOX_ID: 'mWebAirBookingPurchaseBtmAd1',
  GLOBAL_NAV_TOP_MBOX_ID: 'mWebGlobalNavTop',
  GLOBAL_NAV_PROMO1_MBOX_ID: 'mWebGlobalNavPromo1',
  OFFERS_PAGE_OFFER1_MBOX_ID: 'mWebOffersPageOffer1',
  OFFERS_PAGE_OFFER2_MBOX_ID: 'mWebOffersPageOffer2',
  EARLY_BIRD_PURCHASE_VISIBILITY_MBOX_ID: 'mWebAirPurchaseEarlyBirdBanner',
  EARLY_BIRD_PRICE_VISIBILITY_MBOX_ID: 'mWebAirPriceEarlyBirdBanner',
  RECENT_FLIGHT_DESTINATION_AIRPORT: 'recentFlightDestinationAirport',
  PURCHASE_PAYMENT_METHOD_MBOX_ID: 'mWebAirPurchasePaymentMethod',
  PURCHASE_PAYMENT_METHOD_UPLIFT_DISPLAY: 'mWebAirPurchasePaymentMethodUpliftDisplay',
  CONFIRMATION_PLACEMENT_MBOX_ID: 'mWebCheckoutConfirmationBottomPromo1',
  UPGRADED_BOARDING_PURCHASE_PROMO_TOP_01_MBOX_ID: 'mWebUpgradedBoardingPurchasePromoTop01',
  CHASE_AUDIENCE_WCM_CONTEXT: 'AudienceContextForWCM',
  CHASE_EXISTING_CARD_MEMBER: 'ecm',
  CHECK_IN_CONFIRMATION_UPGRADE_BUTTON: 'mWebCheckInConfirmationUpgradeButton',
  AIRPORTS_MULTI_GROUP_SELECT: 'airBookingIndexWidgetOrigDestMultiSelectGroupDisplay',
  PURCHASE_PAGE_SPLIT_PAY_DISPLAY: 'mWebAirPurchaseApplyPointsDisplay'
};
