export default {
  CONTACT_METHOD_HELPER_I18N_MAP: {
    ALL: 'SHARED__CONTACT_METHOD_HELPER__ALL',
    TEXT: 'SHARED__CONTACT_METHOD_HELPER__TEXT',
    CALL: 'SHARED__CONTACT_METHOD_HELPER__CALL',
    EMAIL: 'SHARED__CONTACT_METHOD_HELPER__EMAIL'
  }
};
