export default {
  GATE: {
    EMPTY: 'N/A',
    DEFAULT: '---'
  },
  TRAVEL_TIME: 'TRAVEL TIME',
  TOTAL_TRAVEL_TIME: 'TOTAL TRAVEL TIME',
  CONFIRMATION: 'CONFIRMATION #',
  DEPARTURE_TIME: 'DEPARTS',
  DEPARTING: 'DEPARTING',
  RETURNING: 'RETURNING',
  CHANGE_PLANES: 'CHANGE PLANES'
};
