export const AIRBOOKING_BILLING_ADDRESS_FORM = 'AIRBOOKING_BILLING_ADDRESS_FORM';
export const AIRBOOKING_PASSENGER_INFO_EDIT = 'AIRBOOKING_PASSENGER_INFO_EDIT';
export const AIRBOOKING_PASSENGER_PERSONAL_INFO_FORM = 'AIRBOOKING_PASSENGER_PERSONAL_INFO_FORM';
export const AIRBOOKING_PURCHASE_SUMMARY_FORM = 'AIRBOOKING_PURCHASE_SUMMARY_FORM';
export const AIRBOOKING__PASSPORT_FORM = 'AIRBOOKING_PASSPORT_FORM';
export const AIR_BOOKING_ADD_MANUAL_IRN = 'AIR_BOOKING_ADD_MANUAL_IRN';
export const AIR_BOOKING_APPLY_RAPID_REWARDS_FORM = 'AIR_BOOKING_APPLY_RAPID_REWARDS_FORM';
export const AIR_BOOKING_CONTACT_METHOD_FORM = 'AIR_BOOKING_CONTACT_METHOD_FORM';
export const AIR_BOOKING_INFO_CONTACT_TRAVEL_MANAGER_FORM = 'AIR_BOOKING_INFO_CONTACT_TRAVEL_MANAGER_FORM';
export const AIR_BOOKING_PARENT_OR_GUARDIAN_FORM = 'AIR_BOOKING_PARENT_OR_GUARDIAN_FORM';
export const AIR_BOOKING_PAYMENT_EDIT_FORM = 'AIR_BOOKING_PAYMENT_EDIT_FORM';
export const AIR_BOOKING_PAYMENT_FORM = 'AIR_BOOKING_PAYMENT_FORM';
export const AIR_BOOKING_SHOPPING_SEARCH_FORM = 'AIR_BOOKING_SHOPPING_SEARCH_FORM';
export const AIR_BOOKING_SPECIAL_ASSISTANCE_FORM = 'AIR_BOOKING_SPECIAL_ASSISTANCE_FORM';

export const AIR_CANCEL_REFUND_QUOTE_FORM = 'AIR_CANCEL_REFUND_QUOTE_FORM';
export const AIR_CANCEL_SELECT_BOUND_FORM = 'AIR_CANCEL_SELECT_BOUND_FORM';
export const AIR_CANCEL_SELECT_PASSENGERS_FORM = 'AIR_CANCEL_SELECT_PASSENGERS_FORM';
export const AIR_CANCEL_SUMMARY_FORM = 'AIR_CANCEL_SUMMARY_FORM';

export const AIR_CHANGE_CONTACT_METHOD_FORM = 'AIR_CHANGE_CONTACT_METHOD_FORM';
export const AIR_CHANGE_PAYMENT_FORM = 'AIR_CHANGE_PAYMENT_FORM';
export const AIR_CHANGE_REACCOM_CONFIRM_FORM = 'AIR_CHANGE_REACCOM_CONFIRM_FORM';
export const AIR_CHANGE_REVIEW_FORM = 'AIR_CHANGE_REVIEW_FORM';
export const AIR_CHANGE_SELECT_FORM = 'AIR_CHANGE_SELECT_FORM';
export const AIR_CHANGE_SELECT_PASSENGERS_FORM = 'AIR_CHANGE_SELECT_PASSENGERS_FORM';
export const AIR_CHANGE_SHOPPING_SEARCH_FORM = 'AIR_CHANGE_SHOPPING_SEARCH_FORM';

export const AIR_UPGRADE_SELECT_BOUNDS_FORM = 'AIR_UPGRADE_SELECT_BOUNDS_FORM';

export const CAR_BOOKING_DISCOUNT_FORM = 'CAR_BOOKING_DISCOUNT_FORM';
export const CAR_BOOKING_DRIVER_INFO_EDIT_FORM = 'CAR_BOOKING_DRIVER_INFO_EDIT_FORM';
export const CAR_BOOKING_PRICING_FORM = 'CAR_BOOKING_PRICING_FORM';
export const CAR_BOOKING_PURCHASE_FORM = 'CAR_BOOKING_PURCHASE_FORM';
export const CAR_BOOKING_SEARCH_FORM = 'CAR_BOOKING_SEARCH_FORM';

export const CHECK_IN_ADDITIONAL_PASSPORT_INFO_FORM = 'CHECK_IN_ADDITIONAL_PASSPORT_INFO_FORM';
export const CHECK_IN_APIS_DESTINATION_FORM = 'CHECK_IN_APIS_DESTINATION_FORM';
export const CHECK_IN_APIS_PERMANENT_RESIDENT_CARD_FORM = 'CHECK_IN_APIS_PERMANENT_RESIDENT_CARD_FORM';
export const CHECK_IN_APIS_VISA_FORM = 'CHECK_IN_APIS_VISA_FORM';
export const CHECK_IN_CHOOSE_MOBILE_BOARDING_PASSES = 'CHECK_IN_CHOOSE_MOBILE_BOARDING_PASSES';
export const CHECK_IN_CONTACT_INFO_FORM = 'CHECK_IN_CONTACT_INFO_FORM';
export const CHECK_IN_PASSPORT_FORM = 'CHECK_IN_PASSPORT_FORM';
export const CHECK_IN_RETRIEVE_RESERVATION_FORM = 'CHECK_IN_RETRIEVE_RESERVATION_FORM';

export const COMPANION_BILLING_ADDRESS_FORM = 'COMPANION_BILLING_ADDRESS_FORM';
export const COMPANION_CONTACT_METHOD_FORM = 'COMPANION_CONTACT_METHOD_FORM';
export const COMPANION_PASSENGER_PERSONAL_INFO_EDIT_FORM = 'COMPANION_PASSENGER_PERSONAL_INFO_EDIT_FORM';
export const COMPANION_PASSENGER_PERSONAL_INFO_FORM = 'COMPANION_PASSENGER_PERSONAL_INFO_FORM';
export const COMPANION_PAYMENT_EDIT_FORM = 'COMPANION_PAYMENT_EDIT_FORM';
export const COMPANION_PAYMENT_FORM = 'COMPANION_PAYMENT_FORM';
export const COMPANION_PURCHASE_SUMMARY_FORM = 'COMPANION_PURCHASE_SUMMARY_FORM';
export const COMPANION_SPECIAL_ASSISTANCE_FORM = 'COMPANION_SPECIAL_ASSISTANCE_FORM';

export const CREDIT_CARD_UPDATE_FORM = 'CREDIT_CARD_UPDATE_FORM';

export const DAY_OF_TRAVEL_CONTACT_METHOD_FORM = 'DAY_OF_TRAVEL_CONTACT_METHOD_FORM';

export const EARLY_BIRD_CHECK_IN_FORM = 'EARLY_BIRD_CHECK_IN_FORM';
export const EARLY_BIRD_DETAILS_FORM = 'EARLY_BIRD_DETAILS_FORM';
export const EARLY_BIRD_PAYMENT_EDIT_FORM = 'EARLY_BIRD_PAYMENT_EDIT_FORM';
export const EARLY_BIRD_REVIEW_FORM = 'EARLY_BIRD_REVIEW_FORM';

export const ENROLL_CONTACT_INFO_FORM = 'ENROLL_CONTACT_INFO_FORM';
export const ENROLL_PERSONAL_INFO_FORM = 'ENROLL_PERSONAL_INFO_FORM';
export const ENROLL_SECURITY_INFO_FORM = 'ENROLL_SECURITY_INFO_FORM';

export const FLIGHT_STATUS_SEARCH_FORM = 'FLIGHT_STATUS_SEARCH_FORM';

export const LOGIN_FORM = 'LOGIN_FORM';

export const MULTI_SELECT_GROUP_FORM_DESTINATION = 'MULTI_SELECT_GROUP_FORM_DESTINATION';
export const MULTI_SELECT_GROUP_FORM_ORIGIN = 'MULTI_SELECT_GROUP_FORM_ORIGIN';

export const RELOGIN_FORM = 'RELOGIN_FORM';

export const SAME_DAY_PAYMENT_FORM = 'SAME_DAY_PAYMENT_FORM';
export const SAME_DAY_PRICE_DIFFERENCE_FORM = 'SAME_DAY_PRICE_DIFFERENCE_FORM';
export const SAME_DAY_REFUND_METHOD_FORM = 'SAME_DAY_REFUND_METHOD_FORM';
export const SAME_DAY_REVIEW_FORM = 'SAME_DAY_REVIEW_FORM';
export const SAME_DAY_SELECT_FORM = 'SAME_DAY_SELECT_FORM';
export const SAME_DAY_SORT_FILTER_FORM = 'SAME_DAY_SORT_FILTER_FORM';
export const SAME_DAY_STANDBY_PRICE_DIFFERENCE_FORM = 'SAME_DAY_STANDBY_PRICE_DIFFERENCE_FORM';

export const TRANSFER_TRAVEL_FUNDS_FORM = 'TRANSFER_TRAVEL_FUNDS_FORM';

export const UNKNOWN_FORM_ID = 'UNKNOWN_FORM_ID';

export const UPGRADE_FARE_RETRIEVE_RESERVATION_FORM = 'UPGRADE_FARE_RETRIEVE_RESERVATION_FORM';

export const UPGRADED_BOARDING_FORM = 'UPGRADED_BOARDING_FORM';
export const UPGRADED_BOARDING_PAYMENT_EDIT_FORM = 'UPGRADED_BOARDING_PAYMENT_EDIT_FORM';
export const UPGRADED_BOARDING_PURCHASE_FORM = 'UPGRADED_BOARDING_PURCHASE_FORM';

export const VIEW_RESERVATIONS_RETRIEVE_CAR_RESERVATION_FORM = 'VIEW_RESERVATIONS_RETRIEVE_CAR_RESERVATION_FORM';
export const VIEW_RESERVATIONS_RETRIEVE_RESERVATION_FORM = 'VIEW_RESERVATIONS_RETRIEVE_RESERVATION_FORM';
export const VIEW_RESERVATION_SPECIAL_ASSISTANCE_FORM = 'VIEW_RESERVATION_SPECIAL_ASSISTANCE_FORM';
export const VIEW_RESERVATION_TRAVEL_INFORMATION_FORM = 'VIEW_RESERVATION_TRAVEL_INFORMATION_FORM';
