export const LOGIN_SHOW_SHORT_TEXT = 'LOGIN_SHOW_SHORT_TEXT';
export const LOGIN_SHOW_LONG_TEXT = 'LOGIN_SHOW_LONG_TEXT';
export const EDIT_SHOW_EDIT_TEXT = 'EDIT_SHOW_EDIT_TEXT';
export const EDIT_SHOW_CANCEL_TEXT = 'EDIT_SHOW_CANCEL_TEXT';
export const HIDDEN = 'HIDDEN';
