export default {
  HOLD_FOR_FUTURE_USE: 'HOLD_FOR_FUTURE_USE',
  REFUND_TO_CREDIT_CARD: 'REFUND_TO_CREDIT_CARD',
  HOLD_FUTURE_USE: 'HOLD_FUTURE_USE',
  BACK_TO_ORIGINAL_PAYMENT: 'BACK_TO_ORIGINAL_PAYMENT'
};
