export default {
  MESSAGE_GOVERNMENT_APPROVAL_TITLE: 'MESSAGE_GOVERNMENT_APPROVAL_TITLE',
  MESSAGE_GOVERNMENT_APPROVAL_TEXT: 'MESSAGE_GOVERNMENT_APPROVAL_TEXT',
  MESSAGE_GOVERNMENT_APPROVAL: 'MESSAGE_GOVERNMENT_APPROVAL'
};
