export default {
  HIDE_RE_LOGIN_MODAL: 'HIDE_RE_LOGIN_MODAL',
  IS_RE_LOGIN_POINTS_BOOKING: 'IS_RE_LOGIN_POINTS_BOOKING',
  SHOW_RE_LOGIN_MODAL: 'SHOW_RE_LOGIN_MODAL',
  SET_RE_LOGIN_CALLBACK_FUNCTIONS: 'SET_RE_LOGIN_CALLBACK_FUNCTIONS',
  RETRY_FUNCTIONS: 'RETRY_FUNCTIONS'
};
