module.exports = {
  elements: {
    tripBookedMessage: '.trip-booked',
    destinationAirport: '.trip-date-dest-city--destination-airport',
    userName: '.confirmation-trip-header--passenger-name',
    pnr: '.passenger-record-locator',
    rapidRewardsAccount: '.confirmation-trip-header--account-number',
    flightSummaryCard: '.flight-summary-card',
    flightSummaryDeparting: '.flight-summary-departing',
    flightSummaryReturning: '.flight-summary-returning',
    totalAmount: '.refund-total-item-currency',
    fareBreakdown: '[data-qa=confirmation-summary-fare-breakdown]',
    billing: '.billing-info',
    fundResultsList: '.fund-results-list',
    streetOne: '.street-one',
    streetTwo: '.street-two',
    locationInfo: '.location-info',
    fundResultTitle: '.fund-result-title',
    lastFourDigitsText: '.last-four-digits-text',
    creditCardImage: '.credit-card--image',
    creditCardType: '.credit-card--info_name',
    creditCardLastFourNumber: '.credit-card--info_number',
    originalPaidForDollarsUpgrade: '.billing-info--amount-applied:nth-child(1)',
    additionalPaidForDollarsUpgrade: '.billing-info--amount-applied:nth-child(2)',
    originalPaid: '[data-qa="confirmation-summary-original-paid"]',
    additionalPaid: '[data-qa="confirmation-summary-additional-paid-or-refund"]',
    bottomDescription: '[data-qa="confirmation-summary-bottom-description"]',
    cardHolder: '.card-holder',
    billingAddress: '.billing-address',
    confirmationSodaBanner: '[data-qa="confirmation-soda-banner"]',
    travelFundsDetails: '[data-qa="travel-funds-per-passenger-details"]',
    originalPrice: '[data-qa="original-price"]',
    travelFundsRemaining: '[data-qa="passenger-travel-funds"]',
    amountRefunded: '[data-qa="refund-summary-amount-refunded"]',
    travelFundsMsg: '[data-qa="refund-summary-travel-funds-message"]',
    refundMethodMsg: '[data-qa="refund-method"]',
    paypalImage: '.credit-card--image_paypal',
    priceLineTitle: '.refund-total-item--message',
    applePayImage: '.credit-card--image_apple-pay',
    secondFundResultTitle: '.fund-results-list--item:nth-of-type(2) .fund-result-title',
    secondFundLastFourDigits: '.fund-results-list--item:nth-of-type(2) .last-four-digits-text'
  }
};
