export const REQUIRED_ERROR = 'REQUIRED_ERROR';
export const FIELD_ERROR_MESSAGE = 'FIELD_ERROR_MESSAGE';
export const ERROR_HEADER = 'ERROR_HEADER';
export const SIMPLE_ERROR_POPUP = 'SIMPLE_ERROR_POPUP';
export const API_ERROR_POPUP = 'API_ERROR_POPUP';

export const DEFAULT_ERROR_TYPE = FIELD_ERROR_MESSAGE;
