module.exports = {
  LUV_API: '/api/',
  LOGGING_API: '/api/',
  CAR_API: '/api/',
  SECURITY_API: '/security/',
  CHAPI_MISC: '/chapi/',
  CHAPI_AIR_OPERATIONS: '/chapi/',
  CHAPI_AIR_BOOKING: '/chapi/',
  CHAPI_AIR_SHOPPING: '/chapi/',
  ANALYTICS_URL: '/content/app/scripts/analytics/analytics.js',
  USER_CAN_CHANGE_TOGGLES: true,
  BRANCH_KEY: 'key_test_kiCmZHbV9GYaXUX4au1dMeoewweY08T9',
  API_GATEWAY_CHASE_API: '/api/chase/',
  PAYPAL_WEBVIEW_ENV: 'https://www.southwest.com/',
  PAYPAL_WEBVIEW_CANCEL_URL: 'redirect/hybrid/paypal/cancel',
  PAYPAL_WEBVIEW_RETURN_URL: 'redirect/hybrid/paypal/success',
  SWA_VACATIONS_URL: 'https://res.southwestvacations.com/search/ExternalFormPost.aspx?cmpid=SWA-INPATH',
  CHATBOT_BASE_LIVE_AGENT_CONTENT_URL: 'https://c.la1-c1cs-iad.salesforceliveagent.com/content',
  CHATBOT_BASE_LIVE_AGENT_URL: 'https://d.la1-c1cs-iad.salesforceliveagent.com/chat',
  CHATBOT_BUTTON_ID: '5730v0000004Dtl',
  CHATBOT_DEPLOYMENT_ID: '5720v0000004DXv',
  CHATBOT_ESW_LIVE_AGENT_DEV_NAME: 'EmbeddedServiceLiveAgent_Parent04I0v0000008OUzEAM_1754bf9c45e',
  CHATBOT_ORG_ENDPOINT: 'https://config4-swacssinternal.cs66.force.com/connect',
  CHATBOT_ORG_URL: 'https://swac360--config4.my.salesforce.com',
  CHATBOT_ORG_ID: '00D0v000000E32k',
  CHATBOT_EMBEDDED_WINDOW_URL: 'https://swac360--config4.my.salesforce.com/embeddedservice/5.0/esw.min.js'
};
