import { actionCreator } from 'src/shared/redux/actionCreator';

const { createTypes, createApiActions } = actionCreator('airChange');

const types = {
  sync: [
    'CLEAR_SELECTED_PRODUCTS',
    'FLIGHT_PRICING_RESUME_AFTER_LOGIN',
    'REACCOM_CLEAR_SELECTED_PRODUCTS',
    'REACCOM_SAVE_SELECTED_PRODUCTS',
    'REACCOM_SORT_SHOPPING_PAGE_BY',
    'RESET_FLOW_DATA',
    'RESET_PAYMENT_INFO',
    'RESET_REACCOM_CONFIRMATION_PAGE',
    'SAVE_CONTACT_INFORMATION',
    'SAVE_PAYMENT_INFO',
    'SAVE_PNR',
    'SAVE_REACCOM_COTERMINAL_PRODUCTS',
    'SAVE_REACCOM_PNR',
    'SAVE_SELECTED_BOUNDS',
    'SAVE_SELECTED_FLIGHT',
    'SAVE_SELECTED_PRODUCTS',
    'SAVE_SHOPPING_SEARCH_REQUEST',
    'SET_FLOW_STATUS',
    'SORT_SHOPPING_PAGE_BY',
    'UPDATE_CONTACT_METHOD',
    'UPDATE_SHOULD_FORBID_FORWARD'
  ],
  async: [
    'FETCH_RESERVATION_CHANGEABLE',
    'FETCH_FLIGHT_SHOPPING',
    'FETCH_FLIGHT_PRICING',
    'FETCH_PASSENGER_INFO_AND_PAYMENT_OPTIONS',
    'FETCH_PASSENGER_INFO',
    'FETCH_PAYMENT_OPTIONS',
    'FETCH_CHANGE_FLIGHT_CONFIRMATION',
    'FETCH_REACCOM_FLIGHT_PAGE',
    'FETCH_REACCOM_FLIGHT_SHOPPING',
    'FETCH_REACCOM_CONFIRMATION_PAGE',
    'FETCH_SPLIT_PNR_RESERVATION'
  ]
};

export const apiActionCreator = createApiActions;
export default createTypes(types);
