export default {
  OAUTH_LOGIN_STATUS: 'OAUTH_LOGIN_STATUS',
  WEB_VIEW_CHANNEL: 'LocalStorageCache::webViewChannel',
  WEB_VIEW_CORPORATE_CHANNEL: 'LocalStorageCache::webViewCorporateChannel',
  WEB_VIEW_API_KEY: 'LocalStorageCache::webViewApiKey',
  WEB_VIEW_EXPERIENCE_ID: 'LocalStorageCache::webViewExperienceId',
  WEB_VIEW_APP_VERSION: 'LocalStorageCache::webViewAppVersion',
  SHOPPING_SEARCH_HISTORY_STORE_KEY: 'ShoppingSearchHistoryStore::searchRequests',
  CAR_SEARCH_HISTORY_STORE_KEY: 'CarBookingSearchHistoryStore::searchRequests',
  AIRPORT_LIST_CACHE_KEY: 'LocalStorageCache::airportList',
  LAST_BOOKABLE_DATE_CACHE_KEY: 'LocalStorageCache::lastBookableDate',
  CAR_LOCATION_CACHE_KEY: 'LocalStorageCache::carLocations',
  CAR_VENDORS_CACHE_KEY: 'LocalStorageCache::carVendors',
  SHOPPING_RESULT_SECURITY_FEE_FOR_POINTS: 'ShoppingResultSecurityFee::securityFeeForPoints',
  ACCOUNT_INFO: 'AccountInfo',
  USERNAME_KEY: 'AccountInfo::userName',
  ACCOUNT_NUMBER_KEY: 'AccountInfo::accountNumber',
  PRODUCT_DEFINITIONS_CACHE_KEY: 'LocalStorageCache::productDefinitions',
  CHASE_PREQUAL_OFFERS_KEY: 'LocalStorageCache::chasePrequalOffers',
  CHASE_SWA_OFFERS_IDENTITY_KEY: 'LocalStorageCache::chaseOffersIdentity',
  CHASE_SESSION_ID_KEY: 'LocalStorageCache::chaseSessionId',
  CHASE_INSTANT_CREDIT_RETURN_URL_KEY: 'LocalStorageCache::chaseInstantCreditReturnUrl',
  FLIGHT_STATUS_CACHE_KEY: 'LocalStorageCache::FlightStatusRecentSearch',
  RECENT_TRIP_SEARCHES_STORE_KEY_TEMPLATE: 'RecentTripSearchesStore::<%= featureName %>',
  PERSISTENT_HISTORY_KEY: 'SessionStorage::persistentHistory',
  APP_STATE_KEY: 'SessionStorage::appState',
  EXPERIENCE_ID_KEY: 'SessionStorage::experienceId',
  PAYPAL_DATA_KEY: 'LocalStorageCache::payPalData',
  BOARDING_PASS_DATA_FOR_REFRESH: 'SessionStorage::boardingPassData',
  RECENT_AIRPORT_SEARCHES_KEY: 'LocalStorageCache::recentAirportSearches',
  NONSEQUENTIAL_BOARDING_FLAG_KEY: 'SessionStorage::nonsequentialBoardingFlag',
  CHECKIN_HAZMAT_ACK_KEY: 'LocalStorageCache:checkinHazmat',
  CORPORATE_BOOKING_SWITCH_INFO_CACHE_KEY: 'LocalStorageCache::corporateBookingSwitchInfo',
  CEPTOR_PERSISTENCE_IDENTIFIER: 'SessionStorage::ceptorPersistenceIdentifier',
  CALENDAR_SCHEDULE_MESSAGE_CACHE_KEY: 'LocalStorageCache::calendarScheduleMessage',
  USER_INFO_CACHE_KEY: 'LocalStorageCache::userInfo'
};
