// @flow

export default {
  CLEAR_FORM_DATA_BY_URL: 'CLEAR_FORM_DATA_BY_URL',
  CLEAR_FORM_DATA_BY_ID: 'CLEAR_FORM_DATA_BY_ID',
  RESET_FORM_DATA: 'RESET_FORM_DATA',
  UPDATE_FORM_FIELD_DATA_VALUE: 'UPDATE_FORM_FIELD_DATA_VALUE',
  UPDATE_FORM_DATA_VALUE: 'UPDATE_FORM_DATA_VALUE',
  RESTRICT_FORM_CHANGE_TO_FIELD_NAME: 'RESTRICT_FORM_CHANGE_TO_FIELD_NAME',
  UNRESTRICT_FORM_CHANGE_TO_FIELD_NAME: 'UNRESTRICT_FORM_CHANGE_TO_FIELD_NAME'
};
